#!/bin/bash

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

POPUP_CLICK_SCRIPT="sketchybar --set $NAME popup.drawing=toggle"

ICON_FONT="Symbols Nerd Font:Regular"
LABEL_FONT="Victor Mono:SemiBold"
ITALIC_FONT="Victor Mono:SemiBold Italic"

$HEIGHT=30

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=0   \
                 padding_right=6  \
                 color=0x00ffffff \
                 corner_radius=8  \
                 y_offset=5 \
                 shadow=off \
                 margin=8

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="$ICON_FONT:16.0"            \
                     icon.color=0xffe5e9f0                  \
                     label.font="$LABEL_FONT:14.0"          \
                     label.color=$COLOR_WHITE               \
                     padding_left=4                         \
                     padding_right=4                        \
                     label.padding_left=0                   \
                     label.padding_right=0                  \
                     icon.padding_left=4                    \
                     icon.padding_right=4

# Items

## Animators
sketchybar --add event lock   "com.apple.screenIsLocked"   \
           --add event unlock "com.apple.screenIsUnlocked" \
                                                           \
           --add item         animator left                \
           --set animator     drawing=off                  \
                              updates=on                   \
                              script="$PLUGIN_DIR/wake.sh" \
           --subscribe        animator lock unlock


## Apple logo
source "$ITEM_DIR/apple.sh"

## Charge status
sketchybar --add item battery left                             \
           --set battery  script="$PLUGIN_DIR/battery.sh"      \
                          update_freq=120                      \
           --subscribe battery system_woke power_source_change \
                                                               \
           --add slider volume left                            \
           --set volume   script="$PLUGIN_DIR/volume.sh"       \
           --subscribe volume volume_change                    \
                                                               \
           --add item left_gap left                            \
           --set left_gap width=10


##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

# source "$ITEM_DIR/spaces.sh"

# SPACE_ICONS=("󰾔" "󱃖" "󰈚" "" "5" "6" "7" "8" "9" "10")
# SPACE_LABELS=("web" "code" "chat" "work" "5" "6" "7" "8" "9" "10")

# for i in "${!SPACE_ICONS[@]}"
# do
#   sid=$(($i+1))
#   sketchybar --add space space.$sid left                                 \
#              --set space.$sid associated_space=$sid                      \
#                               label=${SPACE_LABELS[i]}                   \
#                               label.drawing=off                          \
#                               icon=${SPACE_ICONS[i]}                     \
#                               icon.font="$ICON_FONT:20.0"                \
#                               icon.color=0xffcdcecf                      \
#                               icon.highlight_color=$COLOR_GREEN          \
#                               icon.background.height=2                   \
#                               icon.background.color=$COLOR_GREEN         \
#                               icon.background.y_offset=-13               \
#                               icon.background.corner_radius=2            \
#                               background.color=0xff88c0d0                \
#                               background.corner_radius=5                 \
#                               background.height=20                       \
#                               background.drawing=off                     \
#                               script="$PLUGIN_DIR/space.sh"              \
#                               click_script="yabai -m space --focus $sid"
# done

SPACE_CLICK_SCRIPT="yabai -m space --focus $sid"

sketchybar --add   item spaces_1.label left                          \
           --set   spaces_1.label label=spc                          \
                                  label.width=32                     \
                                  label.align=right                  \
                                  background.padding_left=4          \
                                  label.padding_left=0               \
                                  icon.padding_left=0                \
                                  associated_display=1               \
                                  drawing=on                         \
                                                                     \
           --add   space          space_template left                \
           --set   space_template icon.highlight_color=0xff9dd274    \
                                  label.drawing=off                  \
                                  drawing=off                        \
                                  updates=on                         \
                                  associated_display=1               \
                                  icon.font="$ICON_FONT:22.0"        \
                                  script="$PLUGIN_DIR/space.sh"      \
                                  icon.background.height=2           \
                                  icon.background.y_offset=-13       \
                                  icon.background.corner_radius=5    \
                                  click_script="$SPACE_CLICK_SCRIPT" \
                                                                     \
           --clone spaces_1.web   space_template                     \
           --set   spaces_1.web   associated_space=1                 \
                                  icon=󰾔                             \
                                  icon.highlight_color=$COLOR_RED    \
                                  icon.background.color=$COLOR_RED   \
                                  drawing=on                         \
                                                                     \
           --clone spaces_1.code  space_template                     \
           --set   spaces_1.code  associated_space=2                 \
                                  icon=󱃖                             \
                                  icon.highlight_color=$COLOR_GREEN  \
                                  icon.background.color=$COLOR_GREEN \
                                  drawing=on                         \
                                                                     \
           --clone spaces_1.chat  space_template                     \
           --set   spaces_1.chat  associated_space=3                 \
                                  icon=󰈚                             \
                                  icon.highlight_color=$COLOR_BLUE   \
                                  icon.background.color=$COLOR_BLUE  \
                                  drawing=on                         \
                                                                     \
           --clone spaces_1.work  space_template                     \
           --set   spaces_1.work  associated_space=4                 \
                                  icon=󰴃                             \
                                  icon.highlight_color=$COLOR_YELLOW \
                                  icon.background.color=$COLOR_YELLOW\
                                  drawing=on


##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

sketchybar --add item space_separator left                         \
           --set space_separator icon=                            \
                                 icon.color=$COLOR_CYAN            \
                                 padding_left=8                    \
                                 padding_right=8                   \
                                 label.drawing=off                 \
                                                                   \
           --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
                                 label.padding_right=4             \
           --subscribe front_app front_app_switched

# Add left bar bracket
sketchybar --add bracket left_bar.0 apple.logo battery volume  \
           --set left_bar.0 background.color=$COLOR_BACKGROUND \
                            background.corner_radius=8         \
                            background.height=32               \
                                                               \
           --add bracket left_bar.1 '/space.*/' front_app      \
           --set left_bar.1 background.color=$COLOR_BACKGROUND \
                            background.corner_radius=8         \
                            background.height=32

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right                            \
           --set clock     update_freq=10                    \
                           script="$PLUGIN_DIR/clock.sh"     \
                           icon.padding_left=0               \
                           icon.padding_right=0              \
                           label.padding_left=0              \
                                                             \
            --add item calendar right                        \
            --set calendar update_freq=10000                 \
                           script="$PLUGIN_DIR/calendar.sh"  \
                           icon=                            \
                           background.color=$COLOR_MAGNETA   \
                           background.height=32              \
                           background.corner_radius=8        \
                           background.padding_left=10        \
                           icon.color=$COLOR_BLACK           \
                           label.color=$COLOR_BLACK          \
                           label.font="$ITALIC_FONT:14.0"    \
                           icon.padding_left=10              \
                           label.padding_right=10            \
                                                             \
           --add item wifi right                             \
           --set wifi      script="$PLUGIN_DIR/wifi.sh"      \
                           icon.color=$COLOR_CYAN            \
                           label.font="$ITALIC_FONT:14.0"    \
                           popup.height=35                   \
                           popup.background.border_width=2   \
                           popup.background.corner_radius=4  \
                           popup.background.border_color=$COLOR_CYAN \
                           popup.background.color=$COLOR_BACKGROUND \
           --subscribe     wifi wifi_change                  \
                           mouse.entered mouse.exited        \
                           mouse.exited.global               \
                                                             \
           --add item wifi.details popup.wifi                \
                                                             \
           --add item ram right                              \
           --set ram       script="$PLUGIN_DIR/ram.sh"       \
                           icon=                            \
                           icon.color=$COLOR_YELLOW          \
                           label.color=$COLOR_YELLOW         \
                           update_freq=10                    \
                                                             \
           --add item cpu right                              \
           --set cpu       script="$PLUGIN_DIR/cpu.sh"       \
                           icon=                            \
                           icon.color=$COLOR_RED             \
                           label.color=$COLOR_RED            \
                           update_freq=2                     \
                                                             \
           --add item net_down right                         \
           --set net_down  icon=󰁅                            \
                           icon.highlight_color=$COLOR_RED   \
                           width=0                           \
                           label.font="$LABEL_FONT:10.0"     \
                           y_offset=-5                       \
                                                             \
           --add item net  right                             \
           --set net       script="$PLUGIN_DIR/network.sh"   \
                           icon=󰁝                            \
                           icon.highlight_color=$COLOR_CYAN  \
                           label.font="$LABEL_FONT:10.0"     \
                           y_offset=5                        \
                           update_freq=2                     \
                                                             \
           --add bracket right_bar net net_down cpu ram wifi \
           --set right_bar background.color=$COLOR_BACKGROUND\
                           background.corner_radius=8        \
                           background.height=32              \
                           # background.border_width=2         \
                           # background.border_color=$COLOR_BLUE

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
